version: "2"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: TA
    volumes:
      - ./ta-db/scripts:/docker-entrypoint-initdb.d
      # - ./ta-db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 

  tests:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes:
      - .:/app/src
    working_dir: /app/src 
    command: dotnet test ta-tests
    environment:
      - CONNECTION_STRING="Server=db;Port=5432;Database=TA;User Id=postgres;Password=example;"